version: '3'
services:
  app:
    image: nginxdemos/hello
    container_name: hello-world
    restart: unless-stopped

  proxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    restart: unless-stopped

volumes:
  npm_data:
  npm_letsencrypt:
